In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
b=np.array([[1,2,3],[4,5,6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
c=np.array([[[1,2],[3,4],[5,6],[7,8]]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype=float)

In [8]:
c

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [9]:
a.ndim

1

In [10]:
# np.arange
x=np.arange(1,11)
x.ndim


1

In [11]:
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
np.ones((1,2))
np.zeros((1,2))

array([[0., 0.]])

In [13]:
np.random.random((3,4))

array([[0.6336215 , 0.74837983, 0.1372374 , 0.75833808],
       [0.48656209, 0.88385768, 0.87426838, 0.91381804],
       [0.54953963, 0.93772266, 0.45543284, 0.1612648 ]])

In [14]:
np.linspace(1,5,100,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5])

In [15]:
x=np.identity(3)
x.ndim

2

In [16]:
x=np.array([1,2,3,4,5,6,7,8])

In [17]:
x=x.reshape(1,2,4)
# [[[1, 2],[3, 4]],[[5, 6],[7, 8]]]

In [18]:
x

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [19]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [20]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [21]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [22]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [23]:
dir(a1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [24]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [25]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [26]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [27]:
# scalar operations - DMAS any nparray with any number
# example a2==a3 a2>5 
# vector operations -DMAS any number of nparray of same shape


In [28]:
a1=np.random.random((3,3))

In [29]:
a1=np.round(a1*100)
a1

array([[73., 18., 67.],
       [53., 29., 65.],
       [ 0., 56., 52.]])

In [30]:
np.max(a1)

np.float64(73.0)

In [31]:
np.min(a1)

np.float64(0.0)

In [32]:
np.sum(a1)

np.float64(413.0)

In [33]:
np.prod(a1)

np.float64(0.0)

In [34]:
np.prod(a1,axis=0)
# axis=0 column
# axis=1 row

array([     0.,  29232., 226460.])

In [35]:
np.var(a1,axis=1)

array([606.88888889, 224.        , 650.66666667])

In [36]:
np.cos(a1)

array([[-0.73619272,  0.66031671, -0.5177698 ],
       [-0.91828279, -0.74805753, -0.56245385],
       [ 1.        ,  0.85322011, -0.16299078]])

In [37]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

a2.dot(a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [38]:
np.log(a1)

/var/folders/_q/_hwcw13s0rd58fg3qg70_cx00000gn/T/ipykernel_998/2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[4.29045944, 2.89037176, 4.20469262],
       [3.97029191, 3.36729583, 4.17438727],
       [      -inf, 4.02535169, 3.95124372]])

In [39]:
np.exp(a1)

array([[5.05239363e+31, 6.56599691e+07, 1.25236317e+29],
       [1.04137594e+23, 3.93133430e+12, 1.69488924e+28],
       [1.00000000e+00, 2.09165950e+24, 3.83100800e+22]])

In [40]:
np.ceil(np.random.random((2,3))*100)

array([[  2.,  49.,  90.],
       [ 40., 100.,  47.]])

<h1>INDEXING AND SLICING</h1>

In [41]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [42]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a1[-2]

np.int64(8)

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2[2,3]

np.int64(11)

In [46]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
a3.shape

(2, 2, 2)

In [48]:
a3[1,0,1]

np.int64(5)

In [49]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a1[0:4]

array([0, 1, 2, 3])

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a2[:,2]

array([ 2,  6, 10])

In [53]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [55]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [113]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [115]:
a2[1:2,::3]

array([[4, 7]])

In [116]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [118]:
a3=np.arange(27).reshape(3,3,3)

In [132]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [138]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [139]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [147]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
# ND TO 1 D
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [158]:
a4=np.arange(4).reshape(2,2)
a5=np.arange(5,9).reshape(2,2)
a4
a5

array([[5, 6],
       [7, 8]])

In [ ]:
x=np.hstack((a4,a5))
# np.vstack((a4,a5))

array([[0, 1],
       [2, 3],
       [5, 6],
       [7, 8]])

In [ ]:
np.hsplit(x,2)

TypeError: hsplit() missing 1 required positional argument: 'indices_or_sections'