In [3]:
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]

import sys
import time

# start=time.time()
# for i in range(len(a)):
#     c.append(a[i]+b[i])
# print(time.time()-start)
sys.getsizeof(a)


89095160

In [4]:
import numpy as np
a=np.arange(10000000,dtype=np.int16)
b=np.arange(10000000,20000000)
sys.getsizeof(a)

# start=time.time()
# c=a+b
# print(time.time()-start)

20000112

<h1>FANCY INDEXING</h1>

In [19]:
a=np.arange(24).reshape(6,4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [26]:
    # BOOLEAN INDEXING
import numpy as np

In [31]:
a=np.random.randint(1,100,24).reshape(6,4)

In [32]:
a[a>50]

array([89, 90, 88, 54, 82, 68, 56, 86, 80, 58, 91, 78])

In [40]:
# FIND OUT EVEN NUMBERS
a[(a%2==0 )&( a>50)]

array([90, 88, 54, 82, 68, 56, 86, 80, 58, 78])

In [41]:
a[a%7==0]

array([56, 21, 91])

<h1>BROADCASTING</h1>

In [50]:
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)

# a+b
print(a)
print(b)
# a+b

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [49]:
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)

a+b

array([[0, 2, 4],
       [3, 5, 7]])

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
a=np.arange(5)
b=np.arange(7)
a+b


ValueError: operands could not be broadcast together with shapes (5,) (7,) 

<h1>MATHEMATICAL FORMULAS</h1>

<!-- sigmoid -->

In [61]:
a=np.arange(10)


In [63]:
# SIGMOID

def sigmoid(array):
    return 1/(1+np.exp(array))

sigmoid(a)

array([5.00000000e-01, 2.68941421e-01, 1.19202922e-01, 4.74258732e-02,
       1.79862100e-02, 6.69285092e-03, 2.47262316e-03, 9.11051194e-04,
       3.35350130e-04, 1.23394576e-04])

In [65]:
# MEAN SQUARED ERROR
actual=np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)

In [67]:
print(actual)
print(predicted)

[ 3 10 23 44 44 30 46 10 40 13 48 34 28 36  6  2  6 39 32 34 28 36 16 14
 27]
[ 4  7 35 45 30 40 37  5 45 13 18 39 45 45  6 11  9  2 21 10 32 12  6 47
 19]


In [72]:
def mse(actual,predicted):
   return np.mean((actual-predicted)**2)

In [73]:
print(mse(actual,predicted))

235.12


In [ ]:
# BINARY CROSS ENTROPY